version: '1'

services:
  hh_stat:
    build: .
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
